// js/translate.js
import {S, setState, showToast} from './state.js';
import {saveCa, saveVoc} from './db.js';

export async function translateText(text,srcL,cache){const key=srcL+':'+text.toLowerCase().trim();if(cache[key])return{...cache[key],fromCache:true};const r={translation:"",definition:"",example:"",exampleTranslation:"",fromCache:false,limit:false};const email=S.user?.email||'';const de=email?`&de=${encodeURIComponent(email)}`:'';const isLimit=d=>String(d?.responseStatus)==='403'||/MYMEMORY WARNING|USED ALL AVAILABLE/i.test(d?.responseData?.translatedText||'');try{const res=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${srcL}|es${de}`);const d=await res.json();if(isLimit(d)){r.limit=true;return r}if(d.responseData?.translatedText)r.translation=d.responseData.translatedText;if(d.matches?.length>1){const a=d.matches.find(m=>m.translation!==r.translation&&m.quality&&parseInt(m.quality)>50);if(a)r.definition='También: '+a.translation}}catch{r.translation="Error al traducir"}
if(srcL==="en"){try{const c=text.trim().toLowerCase().replace(/[^a-z'-]/g,"");if(c&&!c.includes(" ")){const dr=await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(c)}`);if(dr.ok){const dd=await dr.json(),m=dd?.[0]?.meanings?.[0],d=m?.definitions?.[0];if(d?.definition){try{const tr=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(d.definition)}&langpair=en|es${de}`);r.definition=(await tr.json()).responseData?.translatedText||d.definition}catch{r.definition=d.definition}}if(d?.example){r.example=d.example;try{const er=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(d.example)}&langpair=en|es${de}`);r.exampleTranslation=(await er.json()).responseData?.translatedText||""}catch{}}}}}catch{}}
if(!r.limit)cache[key]={translation:r.translation,definition:r.definition,example:r.example,exampleTranslation:r.exampleTranslation};return r}

export async function handleTranslate(t){const m=S.library.find(x=>x.id===S.currentTextId);setState({translating:true});const r=await translateText(t,m?.language||'en',S.cache);if(r.limit){setState({translating:false});showToast('Límite de traducción gratuito alcanzado por hoy. Intenta de nuevo mañana.','error');return}saveCa();S.popup={...S.popup,translation:r,fromCache:r.fromCache};setState({translating:false})}

export async function translateVocabWord(vocKey){const v=S.vocabulary[vocKey];if(!v)return;setState({translating:vocKey});const r=await translateText(v.word,v.language,S.cache);if(r.limit){setState({translating:false});showToast('Límite de traducción gratuito alcanzado por hoy. Intenta de nuevo mañana.','error');return}saveCa();v.translation=r.translation||v.translation;if(r.definition&&!v.note)v.note=r.definition;if(r.example&&!v.example)v.example=r.example;if(r.exampleTranslation&&!v.exampleTranslation)v.exampleTranslation=r.exampleTranslation;v.dateModified=new Date().toISOString();saveVoc();setState({translating:false})}
