// js/views.js
import {LANGS, LEVELS, I, SM2Q, SM2L} from './config.js';
import {S, setState} from './state.js';
import {getStreak, escapeHtml, cleanDefs} from './utils.js';
import {doLogin, doRegister, doResetPassword} from './auth.js';
import {getStats, getComprehension, getWeeklyData, getAllTags, wordStyle, saveReadPos, restoreReadPos, addTag} from './actions.js';

// ══════ RENDER ══════
export function render(){const app=document.getElementById('app');app.style.display='flex';app.style.flexDirection='column';app.style.minHeight='100vh';
if(!S.user){const isL=S.authView==='login';app.innerHTML=`<div class="auth-container"><div class="auth-card card" style="padding:40px 30px"><div style="text-align:center;margin-bottom:32px">${I.bookMarked.replace('24px','40px').replace('24px','40px')}<h1 style="font-size:28px;font-weight:700;color:var(--text);font-family:'Fraunces',serif;margin-top:12px">LinguaReader</h1><p style="color:var(--text3);font-size:14px;margin-top:4px">Tu lector de idiomas con repaso integrado</p></div><h2 style="font-size:18px;font-weight:600;color:var(--text);margin-bottom:20px;text-align:center">${isL?'Iniciar sesión':'Crear cuenta'}</h2>${!isL?'<div class="auth-input"><input class="input" id="a-name" placeholder="Tu nombre"></div>':''}<div class="auth-input"><input class="input" id="a-email" type="email" placeholder="Email"></div><div class="auth-input"><input class="input" id="a-pass" type="password" placeholder="Contraseña"></div>${S.authError?`<div class="auth-error">${S.authError}</div>`:''}<button class="btn btn-primary" id="a-sub" style="width:100%;justify-content:center;padding:12px;font-size:15px;margin-bottom:16px" ${S.authLoading?'disabled':''}>${S.authLoading?I.load+' Cargando...':(isL?'Entrar':'Crear cuenta')}</button>${isL?'<p style="text-align:center;margin-bottom:12px"><a href="#" id="a-forgot" style="color:var(--accent);font-size:13px;text-decoration:none">¿Olvidaste tu contraseña?</a></p>':''}<p style="text-align:center;color:var(--text3);font-size:14px">${isL?'¿No tienes cuenta?':'¿Ya tienes cuenta?'} <a href="#" id="a-tog" style="color:var(--accent);font-weight:600;text-decoration:none">${isL?'Regístrate':'Inicia sesión'}</a></p></div></div>`;
document.getElementById('a-sub')?.addEventListener('click',()=>{const e=document.getElementById('a-email').value.trim(),p=document.getElementById('a-pass').value;if(isL)doLogin(e,p);else doRegister(e,p,document.getElementById('a-name').value.trim())});
document.getElementById('a-pass')?.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('a-sub').click()});
document.getElementById('a-tog')?.addEventListener('click',e=>{e.preventDefault();setState({authView:isL?'register':'login',authError:''})});
document.getElementById('a-forgot')?.addEventListener('click',e=>{e.preventDefault();const email=document.getElementById('a-email').value;doResetPassword(email)});return}
if(S.loading){app.innerHTML=`<div style="display:flex;align-items:center;justify-content:center;height:100vh;gap:12px">${I.load.replace('16px','32px').replace('16px','32px')}<span style="color:var(--text3)">Cargando...</span></div>`;return}

const st=getStats();const streak=getStreak(S.streakHistory);const userName=S.user.displayName||S.user.email?.split('@')[0]||'';
let h='';

// Header
h+=`<header><div style="display:flex;align-items:center;gap:10px">${I.bookMarked}<span style="font-family:'Fraunces',serif;font-weight:600;font-size:22px;color:var(--text);letter-spacing:-.5px">Lingua<em style="font-style:italic;color:var(--accent)">Reader</em></span><span style="font-family:var(--mono);font-size:9px;letter-spacing:.18em;text-transform:uppercase;color:var(--text4)">Est. MMXXVI</span></div><div style="display:flex;gap:4px;align-items:center">
<button class="btn-ghost" onclick="setState({darkMode:!S.darkMode})" style="padding:6px" title="Modo oscuro">${S.darkMode?I.sun:I.moon}</button>
<button class="btn-ghost" onclick="doLogout()" style="padding:6px;color:var(--text4)" title="${escapeHtml(userName)}">${I.out}</button>
</div></header>
<div class="bottom-nav">
<button class="nav-btn ${S.view==='library'||S.view==='reader'?'active':''}" onclick="setState({view:'library'})">${I.lib}<span>Biblioteca</span></button>
<button class="nav-btn ${S.view==='vocabulary'?'active':''}" onclick="setState({view:'vocabulary'})">${I.lib}<span>Vocabulario</span></button>
<button class="nav-btn ${S.view==='flashcards'?'active':''}" onclick="setState({view:'flashcards'});startFc()">${I.brain}<span>Repasar</span></button>
<button class="nav-btn ${S.view==='dashboard'?'active':''}" onclick="setState({view:'dashboard'})">${I.chart}<span>Progreso</span></button>
</div><main>`;

// ── LIBRARY ──
if(S.view==='library'){
h+=`<div style="animation:fadeIn .3s"><div style="margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px"><div><div class="kicker" style="margin-bottom:8px">Tu colección</div><h1 style="font-size:clamp(34px,6vw,52px);font-weight:400;font-family:'Fraunces',serif;line-height:1;letter-spacing:-1px">Mi <em style="font-style:italic;color:var(--accent)">Biblioteca</em></h1><p style="color:var(--text3);font-size:13px;font-family:var(--mono);margin-top:12px">${S.library.length} texto${S.library.length!==1?'s':''} · ${streak>0?'🔥 '+streak+' día'+(streak!==1?'s':'')+' de racha':escapeHtml(userName)}</p></div><div style="display:flex;gap:8px"><button class="btn btn-primary btn-sm" onclick="setState({showPasteModal:true})">${I.paste} Pegar texto</button><input type="file" accept=".pdf,.txt,.text,application/pdf,text/plain" onchange="handleFile(event)" style="position:absolute;width:1px;height:1px;opacity:0" id="fu"><label for="fu" class="btn btn-primary btn-sm" style="cursor:pointer">${I.up} Subir archivo</label></div></div>`;
if(st.dueToday>0)h+=`<div class="card" style="margin-bottom:20px;background:linear-gradient(135deg,rgba(188,74,43,.05),var(--bg2));border:1px solid rgba(188,74,43,.2);display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px"><div style="display:flex;align-items:center;gap:12px"><div style="width:42px;height:42px;border-radius:12px;background:var(--accent);display:flex;align-items:center;justify-content:center">${I.brain.replace('currentColor','white')}</div><div><div style="font-weight:600;font-size:15px">${st.dueToday} tarjeta${st.dueToday!==1?'s':''} pendiente${st.dueToday!==1?'s':''}</div><div style="color:var(--text3);font-size:13px">La práctica diaria refuerza tu memoria</div></div></div><button class="btn btn-primary btn-sm" onclick="setState({view:'flashcards'});startFc()">Repasar</button></div>`;
if(!S.library.length)h+=`<div class="card" style="text-align:center;padding:60px">${I.file}<h3 style="font-size:18px;font-weight:600;margin:16px 0 8px">Tu biblioteca está vacía</h3><p style="color:var(--text3);font-size:14px;margin-bottom:20px">Sube un PDF, archivo de texto o pega contenido</p><label for="fu" class="btn btn-primary" style="cursor:pointer;display:inline-flex">${I.up} Subir texto</label></div>`;
else{h+=`<div style="display:flex;flex-direction:column;gap:0">`;let _n=0;for(const it of S.library){const comp=getComprehension(it.id);_n++;
h+=`<div class="card lr-entry" style="cursor:pointer"><div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px"><div style="flex:1;min-width:0;display:flex;gap:14px" onclick="setState({currentTextId:'${it.id}',view:'reader'})"><span class="lr-num">${String(_n).padStart(2,'0')}</span><div style="flex:1;min-width:0"><div style="display:flex;align-items:center;gap:8px;margin-bottom:6px"><h3 style="font-size:22px;font-weight:400;font-family:'Fraunces',serif;line-height:1.1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHtml(it.title)}</h3><span class="tag" style="background:${LEVELS.unknown.bg};color:${LEVELS.unknown.color}">${LANGS[it.language]||'?'}</span>${comp.pct>0?`<span class="tag" style="background:${LEVELS.learned.bg};color:${LEVELS.learned.color}">${comp.pct}% ✓</span>`:''}</div><p style="color:var(--text3);font-size:13px;line-height:1.5;overflow:hidden;text-overflow:ellipsis;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical">${escapeHtml(it.preview)}</p><div style="color:var(--text4);font-size:12px;margin-top:8px">${it.wordCount.toLocaleString()} palabras • ${new Date(it.dateAdded).toLocaleDateString('es')}</div></div></div><div style="display:flex;gap:4px;flex-shrink:0"><select class="input" style="width:100px;padding:6px 30px 6px 8px;font-size:12px" onchange="event.stopPropagation();setTextLang('${it.id}',this.value)" onclick="event.stopPropagation()">${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${k===it.language?'selected':''}>${v}</option>`).join('')}</select><button class="btn-ghost" style="padding:6px;color:#D4563A" onclick="event.stopPropagation();setState({confirmAction:{msg:'¿Eliminar este texto?',id:'${it.id}'}})">${I.trash}</button></div></div></div>`}h+=`</div>`}h+=`</div>`}

// ── READER ──
if(S.view==='reader'&&S.currentTextId){const meta=S.library.find(t=>t.id===S.currentTextId);const text=S.texts[S.currentTextId]||'';const lang=meta?.language||'en';const paras=text.split(/\n\s*\n/).filter(Boolean);const comp=getComprehension(S.currentTextId);const vc={};for(const k of Object.keys(LEVELS))vc[k]=Object.values(S.vocabulary).filter(w=>w.language===lang&&w.level===k).length;
h+=`<div style="animation:fadeIn .3s"><div style="margin-bottom:16px;display:flex;align-items:center;gap:12px"><button class="btn-ghost" onclick="saveReadPos();setState({view:'library'})" style="padding:8px">${I.back}</button><div style="flex:1;min-width:0"><h2 style="font-size:24px;font-weight:400;font-family:'Fraunces',serif;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${escapeHtml(meta?.title||'')}</h2><span style="color:var(--text3);font-size:11px;font-family:var(--mono);letter-spacing:.04em;text-transform:uppercase">${LANGS[lang]} · ${comp.pct}% comprensión · ${comp.known}/${comp.total} palabras</span></div><div class="font-ctrl"><button onclick="setState({selectMode:!S.selectMode})" style="width:auto;padding:4px 10px;font-size:12px;background:${S.selectMode?'var(--accent)':'var(--bg2)'};color:${S.selectMode?'white':'var(--text2)'};border:2px solid ${S.selectMode?'var(--accent)':'var(--border)'}">${S.selectMode?I.cursor+' Seleccionar':I.hand+' Leer'}</button><button onclick="setState({fontSize:Math.max(12,S.fontSize-2)})">A-</button><span style="font-size:12px;color:var(--text3)">${S.fontSize}</span><button onclick="setState({fontSize:Math.min(28,S.fontSize+2)})">A+</button></div></div>`;
h+=`<div style="display:flex;gap:6px;margin-bottom:12px;flex-wrap:wrap">${Object.entries(LEVELS).map(([k,v])=>`<span class="tag" style="background:${v.bg};color:${v.color}"><span style="width:8px;height:8px;border-radius:50%;background:${v.color};display:inline-block"></span> ${v.label}: ${vc[k]}</span>`).join('')}</div>`;
h+=`<div class="card" id="reader-area" style="padding:24px;line-height:2;font-size:${S.fontSize}px;font-family:'Crimson Pro',serif;max-height:65vh;overflow-y:${S.selectMode?'hidden':'auto'};${S.selectMode?'user-select:text;-webkit-user-select:text;touch-action:none;':'user-select:none;-webkit-user-select:none;'}">`;
if(S.selectMode)h+=`<div style="background:rgba(188,74,43,.08);border-radius:8px;padding:8px 12px;margin-bottom:12px;font-size:13px;color:var(--accent);font-family:'DM Sans',sans-serif;text-align:center">Modo selección activo — arrastra el dedo sobre el texto para seleccionar frases</div>`;
for(const para of paras){const toks=para.split(/(\s+)/);h+='<p style="margin-bottom:18px">';for(const tok of toks){if(/^\s+$/.test(tok)){h+=tok;continue}const c=tok.replace(/[.,;:!?¿¡"""''()\[\]{}]/g,'');if(!c){h+=tok;continue}h+=`<span class="word-span" data-word="${escapeHtml(tok)}" style="${wordStyle(c,lang)}">${escapeHtml(tok)}</span>`}h+='</p>'}
h+=`</div><div style="text-align:center;margin-top:10px;color:var(--text4);font-size:13px">${S.selectMode?'Arrastra el dedo para seleccionar frases • Cambia a "Leer" para hacer scroll':'Toca una palabra para traducir • Cambia a "Seleccionar" para elegir frases'}</div></div>`}

// ── VOCABULARY ──
if(S.view==='vocabulary'){const allTags=getAllTags();const filtered=Object.entries(S.vocabulary).filter(([k,v])=>(S.vocabFilter==='all'||v.level===S.vocabFilter)&&(S.vocabLangFilter==='all'||v.language===S.vocabLangFilter)&&(!S.searchTerm||v.word.toLowerCase().includes(S.searchTerm.toLowerCase())||(v.translation||'').toLowerCase().includes(S.searchTerm.toLowerCase())||(v.tags||[]).some(t=>t.includes(S.searchTerm.toLowerCase())))).sort((a,b)=>new Date(b[1].dateModified||b[1].dateAdded)-new Date(a[1].dateModified||a[1].dateAdded));
// Group
let grouped={};if(S.vocabGroupBy==='source'){for(const[k,v]of filtered){const src=S.library.find(t=>t.id===v.sourceTextId);const g=src?.title||'Sin texto';if(!grouped[g])grouped[g]=[];grouped[g].push([k,v])}}else if(S.vocabGroupBy==='tag'){for(const[k,v]of filtered){const tags=(v.tags&&v.tags.length)?v.tags:['Sin etiqueta'];for(const t of tags){if(!grouped[t])grouped[t]=[];grouped[t].push([k,v])}}}else{grouped={'all':filtered};}

h+=`<div style="animation:fadeIn .3s"><div style="display:flex;justify-content:space-between;align-items:flex-start;flex-wrap:wrap;gap:12px;margin-bottom:16px"><div><div class="kicker" style="margin-bottom:8px">Tu léxico</div><h1 style="font-size:clamp(34px,6vw,52px);font-weight:400;font-family:'Fraunces',serif;line-height:1;letter-spacing:-1px">Mi <em style="font-style:italic;color:var(--accent)">Vocabulario</em></h1><p style="color:var(--text3);font-size:13px;font-family:var(--mono);margin-top:12px">${st.total} palabra${st.total!==1?'s':''}</p></div><div style="display:flex;gap:6px"><button class="btn btn-sm ${S.vocabGroupBy==='none'?'btn-primary':'btn-ghost'}" onclick="setState({vocabGroupBy:'none'})">Todo</button><button class="btn btn-sm ${S.vocabGroupBy==='source'?'btn-primary':'btn-ghost'}" onclick="setState({vocabGroupBy:'source'})">Por texto</button><button class="btn btn-sm ${S.vocabGroupBy==='tag'?'btn-primary':'btn-ghost'}" onclick="setState({vocabGroupBy:'tag'})">Por etiqueta</button><button class="btn-ghost btn-sm" onclick="exportCSV()" title="Exportar CSV">${I.dl} CSV</button></div></div>`;
h+=`<div style="display:flex;gap:8px;margin-bottom:12px;flex-wrap:wrap">${Object.entries(LEVELS).map(([k,v])=>{const c=k==='unknown'?st.unknown:k==='recognized'?st.recognized:st.learned;return`<span class="tag" style="background:${v.bg};color:${v.color};cursor:pointer;opacity:${S.vocabFilter===k||S.vocabFilter==='all'?1:.4}" onclick="setState({vocabFilter:S.vocabFilter==='${k}'?'all':'${k}'})">${v.label}: ${c}</span>`}).join('')}</div>`;
h+=`<div style="display:flex;gap:8px;margin-bottom:16px"><div style="flex:1;position:relative"><span style="position:absolute;left:12px;top:50%;transform:translateY(-50%)">${I.search}</span><input class="input" placeholder="Buscar palabra o etiqueta..." value="${escapeHtml(S.searchTerm)}" oninput="setState({searchTerm:this.value})" style="padding-left:36px"></div><select class="input" style="width:110px" onchange="setState({vocabLangFilter:this.value})"><option value="all">Todos</option>${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${S.vocabLangFilter===k?'selected':''}>${v}</option>`).join('')}</select></div>`;

for(const[group,items]of Object.entries(grouped)){
if(S.vocabGroupBy!=='none')h+=`<h3 style="font-size:14px;font-weight:600;color:var(--text3);margin:16px 0 8px;text-transform:uppercase;letter-spacing:.5px">${escapeHtml(group)} (${items.length})</h3>`;
if(!items.length)h+=`<div class="card" style="text-align:center;padding:30px;color:var(--text3)">No hay palabras</div>`;
else{h+=`<div style="display:flex;flex-direction:column;gap:8px;margin-bottom:8px">`;
for(const[key,it]of items){const iew=S.editingWord===key,ien=S.editingNote===key,iet=S.editingTranslation===key;
h+=`<div class="card" style="padding:14px"><div style="display:flex;justify-content:space-between;align-items:flex-start"><div style="flex:1"><div style="display:flex;align-items:center;gap:8px;margin-bottom:4px;flex-wrap:wrap">`;
if(iew)h+=`<div style="display:flex;gap:6px;flex:1"><input class="input" id="ewi" value="${S.wordText.replace(/"/g,'&quot;')}" oninput="S.wordText=this.value" style="flex:1;font-size:15px;padding:4px 10px;font-weight:600"><button class="btn btn-primary btn-sm" onclick="var nk='${it.language}:'+S.wordText.toLowerCase().trim();if(S.wordText.trim()){S.vocabulary[nk]={...S.vocabulary['${key}'],word:S.wordText.trim(),dateModified:new Date().toISOString()};if('${key}'!==nk)delete S.vocabulary['${key}'];if(S.flashcards['${key}']){S.flashcards[nk]=S.flashcards['${key}'];if('${key}'!==nk)delete S.flashcards['${key}'];}saveVoc();saveFc()}setState({editingWord:null})">${I.check}</button><button class="btn-ghost btn-sm" onclick="setState({editingWord:null})">${I.x}</button></div>`;
else h+=`<span style="font-weight:600;font-size:15px;font-family:'Crimson Pro',serif;cursor:pointer" onclick="setState({editingWord:'${key}',wordText:'${it.word.replace(/'/g,"\\'").replace(/"/g,'&quot;')}'})">${escapeHtml(it.word)}</span><span class="tag" style="background:${LEVELS[it.level]?.bg};color:${LEVELS[it.level]?.color};font-size:11px">${LEVELS[it.level]?.label}</span><span style="color:var(--text4);font-size:11px">${LANGS[it.language]}</span><button class="btn-ghost" style="padding:2px" onclick="speak('${it.word.replace(/'/g,"\\'")}','${it.language}')" title="Escuchar">${I.vol}</button>`;
h+=`</div>`;
if(iet)h+=`<div style="margin-top:4px;display:flex;gap:6px"><input class="input" id="eti" value="${(S.translationText||'').replace(/"/g,'&quot;')}" oninput="S.translationText=this.value" style="flex:1;font-size:14px;padding:4px 10px;color:#4D8B52;font-weight:500" placeholder="Traducción..."><button class="btn btn-primary btn-sm" onclick="S.vocabulary['${key}'].translation=S.translationText.trim();S.vocabulary['${key}'].dateModified=new Date().toISOString();saveVoc();setState({editingTranslation:null})">${I.check}</button><button class="btn-ghost btn-sm" onclick="setState({editingTranslation:null})">${I.x}</button></div>`;
else if(it.translation)h+=`<div style="display:flex;align-items:center;gap:6px;margin-bottom:2px"><div style="color:#4D8B52;font-size:14px;font-weight:500;cursor:pointer;flex:1" onclick="setState({editingTranslation:'${key}',translationText:'${(it.translation||'').replace(/'/g,"\\'").replace(/"/g,'&quot;')}'})">${escapeHtml(it.translation)}</div><button class="btn-ghost" style="padding:2px;flex-shrink:0" onclick="translateVocabWord('${key}')" title="Re-traducir">${S.translating==='${key}'?I.load:I.globe}</button></div>`;
else h+=`<div style="display:flex;gap:6px;margin-top:2px"><button class="btn btn-sm" style="background:var(--bg3);color:var(--accent);border:1px solid var(--border)" onclick="translateVocabWord('${key}')">${S.translating==='${key}'?I.load+' Traduciendo...':I.globe+' Traducir'}</button><span style="color:var(--text4);font-size:13px;cursor:pointer;display:flex;align-items:center" onclick="setState({editingTranslation:'${key}',translationText:''})">o escribir manual</span></div>`;
if(ien)h+=`<div style="margin-top:6px;display:flex;gap:6px"><input class="input" id="eni" value="${(S.noteText||'').replace(/"/g,'&quot;')}" oninput="S.noteText=this.value" style="flex:1;font-size:13px;padding:4px 10px" placeholder="Nota..."><button class="btn btn-primary btn-sm" onclick="S.vocabulary['${key}'].note=S.noteText;saveVoc();setState({editingNote:null})">${I.check}</button><button class="btn-ghost btn-sm" onclick="setState({editingNote:null})">${I.x}</button></div>`;
else if(it.note)h+=`<div style="color:var(--text2);font-size:13px;margin-top:4px;font-style:italic">${escapeHtml(it.note)}</div>`;
// Tags
h+=`<div style="margin-top:4px;display:flex;flex-wrap:wrap;align-items:center;gap:2px">`;
if(it.tags)for(const t of it.tags)h+=`<span class="tag-pill">${I.tag} ${escapeHtml(t)} <span onclick="event.stopPropagation();removeTag('${key}','${t}')" style="cursor:pointer;margin-left:2px">×</span></span>`;
h+=`<span class="tag-pill" style="opacity:.5" onclick="setState({showTagModal:'${key}',tagInput:''})">+ etiqueta</span></div>`;
h+=`</div><div style="display:flex;gap:4px;flex-shrink:0"><select class="input" style="width:100px;padding:4px 24px 4px 6px;font-size:11px" onchange="S.vocabulary['${key}'].level=this.value;S.vocabulary['${key}'].dateModified=new Date().toISOString();saveVoc();render()">${Object.entries(LEVELS).map(([k,v])=>`<option value="${k}" ${k===it.level?'selected':''}>${v.label}</option>`).join('')}</select><button class="btn-ghost" style="padding:4px" onclick="setState({editingNote:'${key}',noteText:'${(it.note||'').replace(/'/g,"\\'").replace(/"/g,'&quot;')}'})">${I.edit}</button><button class="btn-ghost" style="padding:4px;color:#D4563A" onclick="setState({confirmAction:{msg:'¿Eliminar?',vocabKey:'${key}'}})">${I.trash}</button></div></div></div>`;
}h+=`</div>`}}h+=`</div>`}

// ── FLASHCARDS ──
if(S.view==='flashcards'){
h+=`<div style="animation:fadeIn .3s"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px;flex-wrap:wrap;gap:12px"><div><div class="kicker" style="margin-bottom:8px">Repetición espaciada</div><h1 style="font-size:clamp(34px,6vw,52px);font-weight:400;font-family:'Fraunces',serif;line-height:1;letter-spacing:-1px">Re<em style="font-style:italic;color:var(--accent)">pasar</em></h1><p style="color:var(--text3);font-size:13px;font-family:var(--mono);margin-top:12px">${streak>0?'🔥 '+streak+' día'+(streak!==1?'s':'')+' de racha':'Estudio diario'}</p></div><select class="input" style="width:120px" onchange="S.fcLangFilter=this.value;startFc()"><option value="all">Todos</option>${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${S.fcLangFilter===k?'selected':''}>${v}</option>`).join('')}</select></div>`;
h+=`<div style="display:flex;gap:8px;margin-bottom:16px"><button class="btn" style="flex:1;justify-content:center;padding:10px;font-size:14px;background:${S.fcMode==='due'?'var(--accent)':'var(--bg2)'};color:${S.fcMode==='due'?'white':'var(--text2)'};border:2px solid ${S.fcMode==='due'?'var(--accent)':'var(--border)'}" onclick="startFc('due')">Pendientes (${st.dueToday})</button><button class="btn" style="flex:1;justify-content:center;padding:10px;font-size:14px;background:${S.fcMode==='all'?'var(--accent)':'var(--bg2)'};color:${S.fcMode==='all'?'white':'var(--text2)'};border:2px solid ${S.fcMode==='all'?'var(--accent)':'var(--border)'}" onclick="startFc('all')">Todas (${st.allCards})</button></div>`;
if(!S.flashcardDeck.length){if(!st.total)h+=`<div class="card" style="text-align:center;padding:50px"><h3 style="font-size:18px;font-weight:600;margin-bottom:8px">Sin vocabulario aún</h3><p style="color:var(--text3);font-size:14px;margin-bottom:16px">Empieza leyendo un texto</p><button class="btn btn-primary" onclick="setState({view:'library'})">Ir a la biblioteca</button></div>`;
else h+=`<div class="card" style="text-align:center;padding:50px">${I.grad}<h3 style="font-size:18px;font-weight:600;margin:16px 0 8px">${S.fcMode==='due'?'¡Todo repasado!':'Sesión completada'}</h3><p style="color:var(--text3);font-size:14px;margin-bottom:16px">${S.fcMode==='due'?'No hay tarjetas pendientes.':'¡Buen trabajo!'}</p><div style="display:flex;gap:8px;justify-content:center;flex-wrap:wrap"><button class="btn btn-primary" onclick="startFc()">${I.redo} Repetir</button>${S.fcMode==='due'&&st.allCards>0?`<button class="btn-ghost" onclick="startFc('all')">Practicar todas (${st.allCards})</button>`:''}</div></div>`}
else{const ck=S.flashcardDeck[S.fcIndex],vi=S.vocabulary[ck];if(vi){
h+=`<div style="text-align:center;margin-bottom:16px;color:var(--text3);font-size:14px">Tarjeta ${S.fcIndex+1} de ${S.flashcardDeck.length}<div style="background:var(--border);border-radius:10px;height:6px;margin-top:8px;overflow:hidden"><div style="background:var(--accent);height:100%;border-radius:10px;width:${((S.fcIndex+1)/S.flashcardDeck.length)*100}%;transition:width .3s"></div></div></div>`;
h+=`<div class="card" style="padding:0;overflow:hidden;animation:flipIn .3s"><div style="padding:${S.fcFlipped?'26px 24px 16px':'48px 30px'};min-height:220px;cursor:pointer" onclick="setState({fcFlipped:!S.fcFlipped})">`;
if(!S.fcFlipped)h+=`<div style="text-align:center"><span class="tag" style="background:${LEVELS[vi.level]?.bg};color:${LEVELS[vi.level]?.color};margin-bottom:14px">${LANGS[vi.language]}</span><div style="font-size:40px;font-weight:400;font-family:'Fraunces',serif;letter-spacing:-.5px;margin:6px 0">${escapeHtml(vi.word)}</div><button class="btn-ghost btn-sm" onclick="event.stopPropagation();speak('${vi.word.replace(/'/g,"\\'")}','${vi.language}')">${I.vol} Escuchar</button><div style="color:var(--text4);font-size:12px;font-family:var(--mono);letter-spacing:.08em;text-transform:uppercase;margin-top:14px">Toca para ver la respuesta</div></div>`;
else{let defs=(vi.definitions&&vi.definitions.length)?vi.definitions:cleanDefs(vi.translation,vi.note);
h+=`<div style="animation:fadeIn .3s"><div style="display:flex;align-items:center;justify-content:center;gap:12px;margin-bottom:6px"><span style="font-size:34px;font-weight:400;font-family:'Fraunces',serif;letter-spacing:-.5px">${escapeHtml(vi.word)}</span><button class="audiobtn" onclick="event.stopPropagation();speak('${vi.word.replace(/'/g,"\\'")}','${vi.language}')" title="Escuchar palabra">${I.vol}</button></div>`;
h+=`<div class="fc-divider"></div><div class="fc-label">definiciones</div>`;
h+=defs.length?`<ul class="deflist">${defs.map(d=>`<li>${escapeHtml(d)}</li>`).join('')}</ul>`:`<div style="color:var(--text4);font-size:15px;font-family:var(--reading)">Sin definición — añádela con el lápiz en Vocabulario</div>`;
if(vi.irregularForms&&vi.irregularForms.length)h+=`<div class="fc-divider"></div><div class="fc-label">formas irregulares</div><div class="pills">${vi.irregularForms.map(f=>`<span class="pill">${escapeHtml(f)}</span>`).join('')}</div>`;
if(vi.example)h+=`<div class="fc-divider"></div><div class="fc-label">ejemplo</div><div class="ex-line"><span class="q">“${escapeHtml(vi.example)}”</span><button class="audiobtn sm" onclick="event.stopPropagation();speak('${(vi.example||'').replace(/'/g,"\\'")}','${vi.language}')" title="Escuchar frase">${I.vol}</button></div>${vi.exampleTranslation?`<div class="ex-tr">${escapeHtml(vi.exampleTranslation)}</div>`:''}`;
h+=`</div>`}
h+=`</div>${S.fcFlipped?`<div style="border-top:1px solid var(--border);padding:14px;display:flex;gap:8px;justify-content:center;flex-wrap:wrap;animation:slideUp .2s">${Object.entries(SM2Q).map(([k,q])=>`<button class="grade-btn" onclick="answerFc(${q})">${SM2L[k]}</button>`).join('')}</div>`:''}</div>`}}h+=`</div>`}

// ── DASHBOARD ──
if(S.view==='dashboard'){const weekly=getWeeklyData();const maxVal=Math.max(...weekly.map(w=>w.added+w.learned),1);
const langDist={};for(const v of Object.values(S.vocabulary)){langDist[v.language]=(langDist[v.language]||0)+1}
h+=`<div style="animation:fadeIn .3s"><div class="kicker" style="margin-bottom:8px">Tu avance</div><h1 style="font-size:clamp(34px,6vw,52px);font-weight:400;font-family:'Fraunces',serif;line-height:1;letter-spacing:-1px;margin-bottom:12px">Mi <em style="font-style:italic;color:var(--accent)">Progreso</em></h1><p style="color:var(--text3);font-size:13px;font-family:var(--mono);margin-bottom:24px">${escapeHtml(userName)} · ${streak>0?'🔥 '+streak+' día'+(streak!==1?'s':'')+' de racha':''}</p>`;
// Streak card
h+=`<div class="card" style="text-align:center;padding:24px;margin-bottom:16px;background:linear-gradient(135deg,rgba(188,74,43,.05),var(--bg2))"><div class="streak-fire">${streak>0?'🔥':'📚'}</div><div style="font-size:36px;font-weight:700;color:var(--accent);margin:8px 0">${streak}</div><div style="color:var(--text3);font-size:14px">día${streak!==1?'s':''} consecutivo${streak!==1?'s':''} estudiando</div></div>`;
// Stats cards
h+=`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin-bottom:20px">`;
h+=`<div class="card" style="text-align:center;padding:16px;border-top:3px solid ${LEVELS.unknown.color}"><div style="font-size:28px;font-weight:700;color:${LEVELS.unknown.color}">${st.unknown}</div><div style="font-size:12px;color:var(--text3)">Desconocidas</div></div>`;
h+=`<div class="card" style="text-align:center;padding:16px;border-top:3px solid ${LEVELS.recognized.color}"><div style="font-size:28px;font-weight:700;color:${LEVELS.recognized.color}">${st.recognized}</div><div style="font-size:12px;color:var(--text3)">Reconozco</div></div>`;
h+=`<div class="card" style="text-align:center;padding:16px;border-top:3px solid ${LEVELS.learned.color}"><div style="font-size:28px;font-weight:700;color:${LEVELS.learned.color}">${st.learned}</div><div style="font-size:12px;color:var(--text3)">Aprendidas</div></div>`;
h+=`<div class="card" style="text-align:center;padding:16px;border-top:3px solid var(--accent)"><div style="font-size:28px;font-weight:700;color:var(--accent)">${st.total}</div><div style="font-size:12px;color:var(--text3)">Total</div></div></div>`;
// Weekly chart
h+=`<div class="card" style="margin-bottom:16px"><h3 style="font-size:15px;font-weight:600;margin-bottom:16px">Últimos 7 días</h3><div class="bar-chart">`;
for(const w of weekly){const h1=Math.max(2,(w.added/maxVal)*100);const h2=Math.max(0,(w.learned/maxVal)*100);
h+=`<div class="bar-col"><div class="bar-value">${w.added+w.learned||''}</div><div style="display:flex;flex-direction:column;justify-content:flex-end;height:100px"><div class="bar-fill" style="height:${h2}px;background:${LEVELS.learned.color}"></div><div class="bar-fill" style="height:${h1}px;background:${LEVELS.unknown.color};border-radius:${h2?'0':'4px 4px'} 0 0"></div></div><div class="bar-label">${w.day}</div></div>`}
h+=`</div><div style="display:flex;gap:16px;margin-top:12px;justify-content:center"><span style="font-size:12px;color:var(--text3)"><span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:${LEVELS.unknown.color};margin-right:4px"></span>Agregadas</span><span style="font-size:12px;color:var(--text3)"><span style="display:inline-block;width:10px;height:10px;border-radius:2px;background:${LEVELS.learned.color};margin-right:4px"></span>Aprendidas</span></div></div>`;
// Language distribution
h+=`<div class="card" style="margin-bottom:16px"><h3 style="font-size:15px;font-weight:600;margin-bottom:16px">Palabras por idioma</h3>`;
for(const[l,c]of Object.entries(langDist).sort((a,b)=>b[1]-a[1])){const pct=Math.round(c/st.total*100);h+=`<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:4px"><span style="font-weight:500">${LANGS[l]||l}</span><span style="color:var(--text3)">${c} (${pct}%)</span></div><div style="background:var(--border);border-radius:6px;height:8px;overflow:hidden"><div style="background:var(--accent);height:100%;border-radius:6px;width:${pct}%;transition:width .5s"></div></div></div>`}
h+=`</div>`;
// Texts comprehension
h+=`<div class="card"><h3 style="font-size:15px;font-weight:600;margin-bottom:16px">Comprensión por texto</h3>`;
for(const it of S.library){const c=getComprehension(it.id);h+=`<div style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:4px"><span style="font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:70%">${escapeHtml(it.title)}</span><span style="color:${c.pct>60?LEVELS.learned.color:c.pct>30?LEVELS.recognized.color:LEVELS.unknown.color};font-weight:600">${c.pct}%</span></div><div style="background:var(--border);border-radius:6px;height:8px;overflow:hidden"><div style="background:${c.pct>60?LEVELS.learned.color:c.pct>30?LEVELS.recognized.color:LEVELS.unknown.color};height:100%;border-radius:6px;width:${c.pct}%;transition:width .5s"></div></div></div>`}
if(!S.library.length)h+=`<p style="color:var(--text3);font-size:14px;text-align:center">Sube textos para ver tu comprensión</p>`;
h+=`</div></div>`}

h+=`</main>`;

// ── POPUP ──
if(S.popup){h+=`<div class="overlay" onclick="if(event.target===this)setState({popup:null})"><div class="card" style="width:100%;max-width:420px;margin:0 16px 16px;animation:slideUp .25s;max-height:80vh;overflow:auto" onclick="event.stopPropagation()"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><h3 style="font-size:14px;font-weight:600;color:var(--text3);text-transform:uppercase">${S.popup.isPhrase?'Frase':'Palabra'}</h3><div style="display:flex;gap:4px"><button class="btn-ghost btn-sm" onclick="speak('${S.popup.text.replace(/'/g,"\\'")}','${(S.library.find(t=>t.id===S.currentTextId)?.language)||'en'}')">${I.vol}</button><button class="btn-ghost" onclick="setState({popup:null})" style="padding:4px">${I.x}</button></div></div><div style="font-size:24px;font-weight:600;font-family:'Crimson Pro',serif;margin-bottom:16px">${escapeHtml(S.popup.text)}</div>`;
if(!S.popup.translation)h+=`<button class="btn btn-primary" style="width:100%;justify-content:center;margin-bottom:16px" ${S.translating?'disabled':''} onclick="handleTranslate('${S.popup.text.replace(/'/g,"\\'")}')">${S.translating?I.load+' Traduciendo...':I.globe+' Traducir'}</button>`;
if(S.popup.translation)h+=`<div style="background:var(--bg3);border-radius:12px;padding:16px;margin-bottom:16px;animation:fadeIn .3s"><div style="font-size:13px;font-weight:600;color:#4D8B52;text-transform:uppercase;margin-bottom:4px;display:flex;align-items:center;gap:8px">Traducción${S.popup.fromCache?' <span style="font-size:10px;font-weight:500;color:var(--text4);text-transform:none;background:var(--border);padding:2px 8px;border-radius:10px">caché</span>':''}</div><div style="font-size:18px;font-weight:500;margin-bottom:8px">${escapeHtml(S.popup.translation.translation)}</div>${S.popup.translation.definition?`<div style="font-size:14px;color:var(--text2);margin-bottom:8px">${escapeHtml(S.popup.translation.definition)}</div>`:''}${S.popup.translation.example?`<div style="font-size:13px;color:var(--text3);border-top:1px solid var(--border);padding-top:8px;margin-top:8px"><strong>Ejemplo:</strong> ${escapeHtml(S.popup.translation.example)}${S.popup.translation.exampleTranslation?'<br><span style="color:var(--text4)">'+escapeHtml(S.popup.translation.exampleTranslation)+'</span>':''}</div>`:''}</div>`;
h+=`<div><div style="font-size:13px;font-weight:600;color:var(--text3);margin-bottom:8px">Guardar como:</div><div style="display:flex;gap:8px">${Object.entries(LEVELS).map(([k,v])=>`<button class="btn" style="flex:1;background:${v.bg};color:${v.color};padding:10px 8px;font-size:13px;justify-content:center;border:2px solid ${v.color}30" onclick="saveWord('${S.popup.text.replace(/'/g,"\\'")}','${k}')">${v.label}</button>`).join('')}</div></div></div></div>`}

// ── PASTE MODAL ──
if(S.showPasteModal){h+=`<div class="overlay" onclick="if(event.target===this)setState({showPasteModal:false})"><div class="card" style="width:100%;max-width:500px;margin:0 16px 16px;animation:slideUp .25s" onclick="event.stopPropagation()"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px"><h3 style="font-size:16px;font-weight:600">Pegar texto</h3><button class="btn-ghost" onclick="setState({showPasteModal:false})" style="padding:4px">${I.x}</button></div><div style="margin-bottom:12px"><input class="input" id="paste-title" placeholder="Título del texto" value="${escapeHtml(S.pasteTitle)}"></div><div style="margin-bottom:12px"><select class="input" id="paste-lang">${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${k===S.pasteLang?'selected':''}>${v}</option>`).join('')}</select></div><div style="margin-bottom:16px"><textarea class="input" id="paste-text" placeholder="Pega aquí el texto en otro idioma..." rows="8">${escapeHtml(S.pasteText)}</textarea></div><button class="btn btn-primary" style="width:100%;justify-content:center" onclick="var t=document.getElementById('paste-text').value,ti=document.getElementById('paste-title').value,la=document.getElementById('paste-lang').value;if(!t.trim()){alert('Escribe o pega un texto');return}S.pasteLang=la;setState({showPasteModal:false,pasteText:'',pasteTitle:''});addText(ti||'Texto pegado',t)">Agregar a mi biblioteca</button></div></div>`}

// ── TAG MODAL ──
if(S.showTagModal){const allT=getAllTags();h+=`<div class="overlay" onclick="if(event.target===this)setState({showTagModal:null})"><div class="card" style="width:100%;max-width:340px;margin:0 16px 16px;animation:slideUp .25s" onclick="event.stopPropagation()"><h3 style="font-size:16px;font-weight:600;margin-bottom:16px">Agregar etiqueta</h3><div style="display:flex;gap:6px;margin-bottom:12px"><input class="input" id="tag-input" placeholder="Nueva etiqueta..." value="${S.tagInput}" oninput="S.tagInput=this.value"><button class="btn btn-primary btn-sm" onclick="addTag('${S.showTagModal}',document.getElementById('tag-input').value)">${I.check}</button></div>${allT.length?`<div style="margin-bottom:8px"><p style="font-size:12px;color:var(--text3);margin-bottom:6px">Etiquetas existentes:</p><div style="display:flex;flex-wrap:wrap;gap:4px">${allT.map(t=>`<span class="tag-pill" onclick="addTag('${S.showTagModal}','${t}')">${t}</span>`).join('')}</div></div>`:''}<button class="btn-ghost" style="width:100%;justify-content:center" onclick="setState({showTagModal:null})">Cancelar</button></div></div>`}

// ── TOAST ──
if(S.toast)h+=`<div class="toast" style="background:${S.toast.type==='error'?'#D4563A':'#4D8B52'}">${S.toast.type==='error'?'⚠ ':'✓ '}${escapeHtml(S.toast.message)}</div>`;

// ── CONFIRM ──
if(S.confirmAction)h+=`<div style="position:fixed;inset:0;background:rgba(0,0,0,.4);z-index:60;display:flex;align-items:center;justify-content:center;padding:20px" onclick="setState({confirmAction:null})"><div class="card" style="max-width:360px;width:100%;animation:slideUp .2s;text-align:center" onclick="event.stopPropagation()"><p style="font-size:16px;font-weight:500;margin-bottom:20px">${S.confirmAction.msg}</p><div style="display:flex;gap:10px"><button class="btn-ghost" style="flex:1;justify-content:center;padding:10px;font-size:14px" onclick="setState({confirmAction:null})">Cancelar</button><button class="btn" style="flex:1;justify-content:center;padding:10px;font-size:14px;background:#D4563A;color:white" onclick="${S.confirmAction.id?`deleteText('${S.confirmAction.id}')`:S.confirmAction.vocabKey?`delete S.vocabulary['${S.confirmAction.vocabKey}'];delete S.flashcards['${S.confirmAction.vocabKey}'];saveVoc();saveFc();setState({confirmAction:null})`:'setState({confirmAction:null})'}">Eliminar</button></div></div></div>`;

app.innerHTML=h;
// Events
const ra=document.getElementById('reader-area');
if(ra){ra.addEventListener('mouseup',handleRI);
if(S.selectMode){let selDebounce=null;const onSelChange=()=>{clearTimeout(selDebounce);selDebounce=setTimeout(()=>{if(S.view!=='reader'||!S.selectMode)return;const sel=window.getSelection();const txt=sel?.toString().trim();if(txt&&txt.length>0&&ra.contains(sel.anchorNode)){const clean=txt.replace(/^[.,;:!?¿¡"""''()\[\]{}]+|[.,;:!?¿¡"""''()\[\]{}]+$/g,'');if(clean)setState({popup:{text:clean,isPhrase:clean.includes(' ')}})}},500)};document.addEventListener('selectionchange',onSelChange);ra._selCleanup=onSelChange}
else{let tY=0,tX=0,tMoved=false;ra.addEventListener('touchstart',e=>{tY=e.touches[0].clientY;tX=e.touches[0].clientX;tMoved=false},{passive:true});ra.addEventListener('touchmove',e=>{if(Math.abs(e.touches[0].clientY-tY)>10||Math.abs(e.touches[0].clientX-tX)>10)tMoved=true},{passive:true});ra.addEventListener('touchend',e=>{if(!tMoved)setTimeout(()=>handleRI(e),50)})}
let scrollSaveT;ra.addEventListener('scroll',()=>{clearTimeout(scrollSaveT);scrollSaveT=setTimeout(saveReadPos,500)});restoreReadPos()}
for(const id of['ewi','eti','eni','tag-input']){const el=document.getElementById(id);if(el)el.focus()}
const tagI=document.getElementById('tag-input');if(tagI)tagI.addEventListener('keydown',e=>{if(e.key==='Enter')addTag(S.showTagModal,tagI.value)});
}

export function handleRI(e){const sel=window.getSelection();const st=sel?.toString().trim();if(st&&st.length>1&&st.includes(' ')){setState({popup:{text:st.replace(/^[.,;:!?¿¡"""''()\[\]{}]+|[.,;:!?¿¡"""''()\[\]{}]+$/g,''),isPhrase:true}});return}const w=e.target?.closest?.('[data-word]');if(w){const clean=w.dataset.word.replace(/^[.,;:!?¿¡"""''()\[\]{}]+|[.,;:!?¿¡"""''()\[\]{}]+$/g,'');if(clean)setState({popup:{text:clean,isPhrase:false}})}}
